apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: controller
    newName: ghcr.io/erikgb/operator-ci-test
    newTag: 0.0.1 # x-release-please-version
resources:
  - manager.yaml
