apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
images:
- name: controller
  newName: project/controller
  newTag: latest
resources:
- manager.yaml
